#!/usr/bin/env python3
"""Generate steal-tech pick decisions + has-stealable trigger from the steal list."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

STEAL_TECHS = [
    "dd_mbt_9", "dd_mbt_8", "dd_mbt_7", "dd_mbt_6", "dd_mbt_5", "dd_mbt_4",
    "dd_ftr_6", "dd_ftr_5b", "dd_ftr_5a", "dd_ftr_45", "dd_ftr_4", "dd_ftr_3",
    "dd_cpu_9", "dd_cpu_8", "dd_cpu_7", "dd_cpu_6", "dd_cpu_5", "dd_cpu_4",
    "dd_inf_8", "dd_inf_7", "dd_inf_6", "dd_inf_5",
    "dd_at_8", "dd_at_7", "dd_at_6",
    "dd_mech_6", "dd_mech_5",
    "dd_cas_6", "dd_cas_5",
    "dd_str_6", "dd_str_5",
    "dd_uav_6", "dd_uav_5",
    "dd_hel_6", "dd_hel_5",
    "dd_esc_7", "dd_esc_6", "dd_esc_5", "dd_esc_4",
    "dd_ssn_6", "dd_ssn_5",
    "dd_ssbn_4",
    "dd_sam_6", "dd_sam_5",
    "dd_spg_7", "dd_rkt_7", "dd_dew_6",
    "jet_engines",
]

DECISIONS = ROOT / "common" / "decisions" / "doomsday_intel_steal_picks.txt"
TRIGGERS = ROOT / "common" / "scripted_triggers" / "doomsday_intel_steal.txt"
LOC = ROOT / "localisation" / "english" / "doomsday_intel_steal_l_english.yml"


def main() -> None:
    stealable = (
        "# Auto-generated by tools/gen_intel_steal_decisions.py — do not edit by hand.\n"
        "dd_intel_has_stealable_tech = {\n"
        "\t# Country scope: has at least one listed tech that ROOT lacks.\n"
        "\tOR = {\n"
        + "\n".join(
            f"\t\tAND = {{\n"
            f"\t\t\thas_tech = {t}\n"
            f"\t\t\tROOT = {{ NOT = {{ has_tech = {t} }} }}\n"
            f"\t\t}}"
            for t in STEAL_TECHS
        )
        + "\n\t}\n}\n"
    )
    TRIGGERS.write_text(stealable, encoding="utf-8")

    decisions = [
        "# Auto-generated by tools/gen_intel_steal_decisions.py — do not edit by hand.",
        "# Shown after Steal Technology map-locks a country (dd_intel_locked).",
        "",
        "doomsday_intel_category = {",
        "",
    ]
    loc_lines = ["l_english:", ""]
    for t in STEAL_TECHS:
        key = f"dd_intel_steal_pick_{t}"
        decisions.append(
            f"\t{key} = {{\n"
            f"\t\ticon = generic_research\n"
            f"\t\tallowed = {{ always = yes }}\n"
            f"\t\tpriority = 40\n"
            f"\t\tvisible = {{\n"
            f"\t\t\tcheck_variable = {{ dd_intel_mission = 6 }}\n"
            f"\t\t\thas_country_flag = dd_intel_locked\n"
            f"\t\t\tvar:dd_intel_mission_target = {{ has_tech = {t} }}\n"
            f"\t\t\tNOT = {{ has_tech = {t} }}\n"
            f"\t\t}}\n"
            f"\t\tcost = 0\n"
            f"\t\tai_will_do = {{ factor = 0 }}\n"
            f"\t\tcomplete_effect = {{\n"
            f"\t\t\tclr_country_flag = dd_intel_steal_ok\n"
            f"\t\t\tif = {{\n"
            f"\t\t\t\tlimit = {{ dd_intel_is_t1 = yes }}\n"
            f"\t\t\t\tset_technology = {{ {t} = 1 }}\n"
            f"\t\t\t\tset_country_flag = dd_intel_steal_ok\n"
            f"\t\t\t}}\n"
            f"\t\t\telse = {{\n"
            f"\t\t\t\tdd_intel_det_flip = yes\n"
            f"\t\t\t\tif = {{\n"
            f"\t\t\t\t\tlimit = {{ check_variable = {{ dd_intel_flip = 0 }} }}\n"
            f"\t\t\t\t\tset_technology = {{ {t} = 1 }}\n"
            f"\t\t\t\t\tset_country_flag = dd_intel_steal_ok\n"
            f"\t\t\t\t}}\n"
            f"\t\t\t}}\n"
            f"\t\t\tvar:dd_intel_mission_target = {{\n"
            f"\t\t\t\tif = {{\n"
            f"\t\t\t\t\tlimit = {{ ROOT = {{ has_country_flag = dd_intel_steal_ok }} }}\n"
            f"\t\t\t\t\tnews_event = {{ id = doomsday_intel.12 hours = 2 }}\n"
            f"\t\t\t\t}}\n"
            f"\t\t\t\telse = {{\n"
            f"\t\t\t\t\tnews_event = {{ id = doomsday_intel.13 hours = 2 }}\n"
            f"\t\t\t\t}}\n"
            f"\t\t\t}}\n"
            f"\t\t\tclr_country_flag = dd_intel_steal_ok\n"
            f"\t\t\tdd_intel_finish_locked = yes\n"
            f"\t\t}}\n"
            f"\t}}\n"
        )
        loc_lines.append(f" {key}:0 \"Steal ${t}$\"")
        loc_lines.append(
            f" {key}_desc:0 \"Copy ${t}$ from [dd_intel_mission_target.GetName]. "
            f"Tier 1 always succeeds; Tier 2: 50%.\""
        )

    decisions.append("}")
    DECISIONS.write_text("\n".join(decisions) + "\n", encoding="utf-8")
    LOC.write_text("\n".join(loc_lines) + "\n", encoding="utf-8-sig")
    print(f"wrote {len(STEAL_TECHS)} steal picks -> {DECISIONS.name}")


if __name__ == "__main__":
    main()
