"""HOI4 loc names -> ISO 3166-2 / 2024-2026 published pops.

Used when Wikidata English labels do not match vanilla state names
(Gorky, Łódz, Batavia, Holland, …). ISO codes are resolved against
tools/data/wikidata_admin1_pop.json. MANUAL_POP is CBS / ONS / census
where Wikidata has no row (Dutch provinces, tiny territories).
"""
from __future__ import annotations

# owner -> {normalized HOI4 name: ISO 3166-2 code(s) to sum}
HOI4_ISO2: dict[str, dict[str, tuple[str, ...]]] = {
    "SOV": {
        "salla": ("RU-KR",),
        "olonets": ("RU-KR",),
        "orel": ("RU-ORL",),
        "sochi": ("RU-KDA",),
        "volgodonsk": ("RU-ROS",),
        "volkhov": ("RU-LEN",),
        "gatchina": ("RU-LEN",),
        "millerovo": ("RU-ROS",),
        "rzhev": ("RU-TVE",),
        "kazan": ("RU-TA",),
        "gorky": ("RU-NIZ",),
        "nizhnynovogrod": ("RU-NIZ",),
        "pechora": ("RU-KO",),
        "tikhvin": ("RU-LEN",),
        "mikhaylovka": ("RU-VGG",),
        "tannutuva": ("RU-TY",),
        "syktyvkar": ("RU-KO",),
        "balakovo": ("RU-SAR",),
        "engels": ("RU-SAR",),
        "vladivostok": ("RU-PRI",),
        "dudinka": ("RU-KYA",),
        "kurilislands": ("RU-SAK",),
        "nikolayevsk": ("RU-KHA",),
        "okhotsk": ("RU-KHA",),
        "chita": ("RU-ZAB",),
        "bodaybo": ("RU-IRK",),
        "bratsk": ("RU-IRK",),
        "zlatoust": ("RU-CHE",),
        "yakutsk": ("RU-SA",),
        "kirensk": ("RU-IRK",),
        "yeniseisk": ("RU-KYA",),
        "surgut": ("RU-KHM",),
        "salekhard": ("RU-YAN",),
        "tobolsk": ("RU-TYU",),
        "northernurals": ("RU-SVE",),
        "magnitogorsk": ("RU-CHE",),
        "kolyma": ("RU-MAG",),
        "ufa": ("RU-BA",),
        "oyrotregion": ("RU-AL",),
        "birobidzhan": ("RU-YEV",),
        "petsamo": ("RU-MUR",),
        "konigsberg": ("RU-KGD",),
        "yamalia": ("RU-YAN",),
        "engelsmarxstadt": ("RU-SAR",),
        "volgagermany": ("RU-SAR",),
        "chukchipeninsula": ("RU-CHU",),
        "chukchipeninsulay": ("RU-CHU",),
        "udachny": ("RU-SA",),
        "verkhoyansk": ("RU-SA",),
        "khatangsky": ("RU-KYA",),
        "kargopol": ("RU-ARK",),
        "kotlas": ("RU-ARK",),
        "torzhok": ("RU-TVE",),
    },
    "UKR": {
        "carpathianruthenia": ("UA-21",),
        "bucovina": ("UA-77",),
        "bocovina": ("UA-77",),
        "stanislawow": ("UA-26",),
        "lwow": ("UA-46",),
        "tarnopol": ("UA-61",),
        "wolyn": ("UA-07", "UA-56"),
        "volhynian": ("UA-07", "UA-56"),
        "odessa": ("UA-51",),
        "chernigov": ("UA-74",),
        "kiev": ("UA-30", "UA-32"),
        "westernkiev": ("UA-30", "UA-32"),
        "kharkov": ("UA-63",),
        "stalino": ("UA-14",),
        "voroshilovgrad": ("UA-09",),
        "southernbessarabia": ("UA-51",),
        "balta": ("UA-51",),
        "kramatorsk": ("UA-14",),
    },
    "POL": {
        "ermlandmasuren": ("PL-28",),
        "hinterpommern": ("PL-32",),
        "westprussen": ("PL-32",),
        "uppersilesia": ("PL-24",),
        "oberschlesien": ("PL-24",),
        "ostmark": ("PL-08",),
        "wartheland": ("PL-08", "PL-30"),
        "danzig": ("PL-22",),
        "poznan": ("PL-30",),
        "lodz": ("PL-10",),
        "bialystok": ("PL-20",),
        "plock": ("PL-14",),
        "mazurskie": ("PL-14",),
        "warsaw": ("PL-14",),
        "katowice": ("PL-24",),
        "gdynia": ("PL-22",),
    },
    "FIN": {
        "lappi": ("FI-LL", "FI-10"),
        "vaasa": ("FI-12", "FI-03", "FI-07"),
        "kuopio": ("FI-15", "FI-13", "FI-05"),
        "turku": ("FI-19", "FI-17", "FI-01"),
        "hame": ("FI-06", "FI-16", "FI-11"),
        "kymi": ("FI-09", "FI-02"),
        "kyme": ("FI-09", "FI-02"),
        "oulu": ("FI-14",),
        "mikkeli": ("FI-04", "FI-08"),
    },
    "ROM": {
        "muntenia": ("RO-B", "RO-IF", "RO-PH", "RO-AG", "RO-DB", "RO-BZ", "RO-BR", "RO-IL", "RO-CL", "RO-GR", "RO-TR"),
        "romania": ("RO-B", "RO-IF", "RO-PH", "RO-AG", "RO-DB", "RO-BZ", "RO-BR", "RO-IL", "RO-CL", "RO-GR", "RO-TR"),
        "moldova": ("RO-IS", "RO-BC", "RO-NT", "RO-SV", "RO-BT", "RO-VS", "RO-GL", "RO-VN"),
        "moldovia": ("RO-IS", "RO-BC", "RO-NT", "RO-SV", "RO-BT", "RO-VS", "RO-GL", "RO-VN"),
        "oltenia": ("RO-DJ", "RO-OT", "RO-VL", "RO-GJ", "RO-MH"),
        "banat": ("RO-TM", "RO-AR", "RO-CS"),
        "crisana": ("RO-BH", "RO-SM"),
        "transylvania": ("RO-CJ", "RO-BV", "RO-SB", "RO-MS", "RO-AB", "RO-HD", "RO-HR"),
        "northtransylvania": ("RO-CJ", "RO-MS", "RO-BN", "RO-MM"),
        "northerntransylvania": ("RO-CJ", "RO-MS", "RO-BN", "RO-MM"),
        "northerndobruja": ("RO-CT", "RO-TL"),
    },
    "INS": {
        "themoluccas": ("ID-MA", "ID-MU"),
        "dutchnewguinea": ("ID-PA", "ID-PB", "ID-PE", "ID-PD"),
        "aruislands": ("ID-MA",),
        "interiorborneo": ("ID-KT", "ID-KU"),
        "padang": ("ID-SB",),
        "medanandriouw": ("ID-SU", "ID-RI", "ID-KR"),
        "atjeh": ("ID-AC",),
        "ajteh": ("ID-AC",),
        "dutchtimor": ("ID-NT",),
        "manado": ("ID-SA", "ID-GO"),
        "batavia": ("ID-JK", "ID-BT"),
    },
    "PAK": {
        "peshawar": ("PK-KP",),
        "sind": ("PK-SD",),
        "southbaluchistan": ("PK-BA",),
        "northbaluchistan": ("PK-BA",),
        "baluchistan": ("PK-BA",),
        "baluchistanstates": ("PK-BA",),
        "sibi": ("PK-BA",),
        "quetta": ("PK-BA",),
        "kalat": ("PK-BA",),
        "waziristan": ("PK-TA",),
        "bahawalpur": ("PK-PB",),
    },
    "SAU": {
        "nejd": ("SA-01",),
        "saudiarabia": ("SA-01",),
        "madinah": ("SA-03",),
        "hejaz": ("SA-03",),
        "jawf": ("SA-12",),
        "asirmakkah": ("SA-02", "SA-14"),
        "najiran": ("SA-10",),
        "dammam": ("SA-04",),
        "rubalkhali": ("SA-01",),
    },
    "KAZ": {
        "akhtubinsk": ("KZ-15",),
        "guryev": ("KZ-23",),
        "krasnyyyar": ("KZ-23",),
        "uralsk": ("KZ-27",),
        "almaata": ("KZ-75", "KZ-19"),
        "kyrgyzstan": ("KZ-75", "KZ-19"),
        "usturt": ("KZ-47",),
        "westernkazakstan": ("KZ-47",),
        "semipalatinsk": ("KZ-10", "KZ-63"),
        "karagandy": ("KZ-35",),
    },
    "FRA": {
        "limousin": ("FR-87", "FR-19", "FR-23"),
        "centresud": ("FR-CVL",),
        "tahiti": ("FR-PF",),
        "kerguelen": ("FR-TF",),
        "stpierreandmiquelon": ("FR-PM",),
        "savoy": ("FR-73", "FR-74"),
        "var": ("FR-83",),
    },
    "SWI": {
        "swissplateau": ("CH-ZH", "CH-BE", "CH-VD", "CH-AG", "CH-GE", "CH-LU", "CH-BL", "CH-BS", "CH-SO", "CH-ZG", "CH-FR"),
        "easternswissalps": ("CH-SG", "CH-GR", "CH-TG", "CH-SZ", "CH-UR", "CH-GL", "CH-AR", "CH-AI", "CH-SH", "CH-OW", "CH-NW"),
        "westernswissalps": ("CH-VS", "CH-TI"),
        "juramountains": ("CH-JU", "CH-NE"),
    },
    "DEN": {
        "jutland": ("DK-81", "DK-82"),
        "southernjutland": ("DK-83",),
        "sonderjylland": ("DK-83",),
        "fyn": ("DK-83",),
    },
    "BEL": {
        "wallonia": ("BE-WAL",),
        "wallonie": ("BE-WAL",),
        "ardennes": ("BE-WLX",),
    },
    "HUN": {
        "northernhungary": ("HU-BU", "HU-PE", "HU-BZ", "HU-HE"),
        "hungary": ("HU-BU", "HU-PE"),
        "transtisza": ("HU-HB", "HU-JN", "HU-BE", "HU-CS", "HU-BK"),
        "southernplain": ("HU-HB", "HU-JN", "HU-BE", "HU-CS", "HU-BK"),
        "northtransdanubia": ("HU-GS", "HU-KE", "HU-FE", "HU-VE", "HU-VA"),
        "westernhungary": ("HU-GS", "HU-KE", "HU-FE", "HU-VE", "HU-VA"),
        "southtransdanubia": ("HU-BA", "HU-SO", "HU-TO", "HU-ZA"),
    },
    "CZE": {
        "northsudetenland": ("CZ-42", "CZ-41"),
        "sudatenland": ("CZ-42", "CZ-41"),
        "southsudetenland": ("CZ-31",),
        "sudetensilesia": ("CZ-80",),
        "eastsudatenland": ("CZ-80",),
        "transolza": ("CZ-80",),
        "zaolzie": ("CZ-80",),
    },
    "LIT": {
        "memel": ("LT-KL",),
        "vilna": ("LT-VL",),
        "suduva": ("LT-MR",),
        "aukstaitija": ("LT-PN", "LT-UT", "LT-AL"),
    },
    "BLR": {
        "polesie": ("BY-BR",),
        "nowogrodek": ("BY-HR",),
        "wilejka": ("BY-MI",),
        "mozyr": ("BY-HO",),
        "pinskmarches": ("BY-BR",),
        "bobruysk": ("BY-MA",),
        "brest": ("BY-BR",),
    },
    "CAN": {
        "princerupert": ("CA-BC",),
        "northwesterncanada": ("CA-BC", "CA-YT", "CA-NT"),
        "haidagwaii": ("CA-BC",),
        "vancouverisland": ("CA-BC",),
        "cotenord": ("CA-QC",),
        "saguenay": ("CA-QC",),
        "maurice": ("CA-QC",),
    },
    "ITA": {
        "puglia": ("IT-75",),
    },
    "SPR": {
        "sevilla": ("ES-SE",),
    },
    "POR": {
        "beja": ("PT-02",),
    },
    "IRE": {
        "connaught": ("IE-C",),
    },
    "NOR": {
        "oslofjord": ("NO-03", "NO-32", "NO-31"),
        "norway": ("NO-03",),
        "helgeland": ("NO-18",),
    },
    "SWE": {
        "smaland": ("SE-G", "SE-H", "SE-F"),
        "bohuslan": ("SE-O",),
    },
    "SLO": {
        "westernslovakia": ("SK-TA", "SK-NI"),
        "slovakia": ("SK-TA",),
        "easternslovakia": ("SK-KI", "SK-PV"),
        "eastslovakia": ("SK-KI", "SK-PV"),
        "southernslovakia": ("SK-NI",),
    },
    "COG": {
        "leopoldville": ("CD-KN", "CD-KC"),
        "congo": ("CD-KN",),
        "stanleyville": ("CD-TO", "CD-IT"),
        "elisabethville": ("CD-HK", "CD-LU"),
        "lusambo": ("CD-KE", "CD-KC", "CD-LO"),
        "kalemie": ("CD-TA",),
        "costermansville": ("CD-SK",),
    },
    "SIA": {
        "isans": ("TH-37",),
    },
    "TUR": {
        "izmit": ("TR-41",),
        "van": ("TR-65",),
    },
    "AUS": {
        "steiermarkkarnten": ("AT-6", "AT-2"),
    },
}

# owner -> {normalized name: (region_key, pop)} when Wikidata has no ISO row.
# Dutch provinces: CBS 2024. Territories: latest census / UN WPP share.
MANUAL_POP: dict[str, dict[str, tuple[str, int]]] = {
    "HOL": {
        "holland": ("holland", 2_960_000 + 3_860_000),
        "brabant": ("brabant", 2_626_000 + 2_134_000 + 1_387_000 + 1_128_000),
        "gelderland": ("brabant", 2_626_000 + 2_134_000 + 1_387_000 + 1_128_000),
        "friesland": ("friesland", 659_000 + 596_000 + 502_000 + 1_184_000 + 445_000 + 391_000),
    },
    "DEN": {
        "bornholm": ("bornholm", 39_600),
        "faroeislands": ("faroe", 54_600),
    },
    "ENG": {
        "pitcairnisland": ("pitcairn", 50),
        "pitcarinisland": ("pitcairn", 50),
        "falklandislands": ("falklands", 3_500),
        "falkandislands": ("falklands", 3_500),
        "turksandcaicos": ("tci", 46_000),
        "southernbahamas": ("tci", 46_000),
        "ascension": ("ascension", 800),
        "sainthelena": ("sthelena", 4_400),
        "diegogarcia": ("diego", 4_000),
        "southgeorgia": ("sgeorgia", 20),
    },
    "USA": {
        "johnstonatoll": ("johnston", 200),
        "midwayisland": ("midway", 40),
        "attuisland": ("attu", 20),
        "guantanamobay": ("gtmo", 6_000),
    },
    "SIA": {
        "westernsiam": ("west", 3_000_000),
        "southernsiam": ("south", 9_400_000),
        "isan": ("isan", 22_000_000),
        "lanna": ("north", 12_000_000),
        "centralsiam": ("central", 22_000_000),
        "easternsiam": ("east", 6_000_000),
    },
    "ETH": {
        "hararghe": ("hararghe", 7_000_000),
        "haraghe": ("hararghe", 7_000_000),
        "bale": ("bale", 2_200_000),
        "sidamo": ("sidamo", 8_000_000),
        "illubaborkaffa": ("illubabor", 3_500_000),
        "illubabor": ("illubabor", 3_500_000),
        "welega": ("welega", 4_000_000),
        "gojjam": ("gojjam", 5_500_000),
        "begemder": ("begemder", 5_000_000),
        "wello": ("wello", 4_000_000),
    },
    "BRM": {
        "magwe": ("magway", 3_900_000),
        "tenasserim": ("tanintharyi", 1_400_000),
        "pegu": ("bago", 4_900_000),
        "irrawaddy": ("ayeyarwady", 6_200_000),
    },
    "NUG": {
        "kentungandyawnghwe": ("shan", 5_800_000),
        "federatedshan": ("shan", 5_800_000),
        "federatedshanstates": ("shan", 5_800_000),
        "arakan": ("rakhine", 3_200_000),
        "sagaing": ("sagaing", 5_300_000),
    },
    "LNA": {
        "libyandesert": ("desert", 80_000),
        "elagheila": ("sirte", 120_000),
        "benghasi": ("benghazi", 800_000),
        "derna": ("derna", 200_000),
        "sirte": ("sirte", 120_000),
        "cyrenaica": ("cyrenaica", 1_200_000),
    },
    "LBA": {
        "tripoli": ("tripoli", 1_200_000),
        "tripolitania": ("tripolitania", 1_800_000),
    },
    "VIN": {
        "southannam": ("annam", 18_000_000),
        "indochina": ("annam", 18_000_000),
        "tonkin": ("tonkin", 38_000_000),
        "annam": ("tonkin", 38_000_000),
        "cochinchina": ("cochin", 22_000_000),
        "mekongdelta": ("cochin", 22_000_000),
    },
    "COG": {
        "coquilhatville": ("equateur", 8_000_000),
        "cameroun": ("equateur", 8_000_000),
    },
    "SAF": {
        "transvaal": ("gauteng-mp-lp-nw", 22_000_000),
        "southafrica": ("gauteng-mp-lp-nw", 22_000_000),
        "cape": ("wc-ec-nc", 16_000_000),
        "sovietlakes": ("wc-ec-nc", 16_000_000),
    },
    "ZAM": {
        "zambia": ("zambia", 18_000_000),
        "barotseland": ("western", 1_100_000),
    },
    "SER": {
        "serbia": ("belgrade", 1_680_000),
        "kosavo": ("belgrade", 1_680_000),
        "morava": ("central", 2_200_000),
        "easternserbia": ("central", 2_200_000),
        "southernserbia": ("south", 1_100_000),
    },
    "ALB": {
        "centralalbania": ("tirana", 919_511),
        "albania": ("tirana", 919_511),
        "northernepirus": ("gjirokaster", 55_000),
    },
    "LAT": {
        "vidzeme": ("vidzeme", 1_200_000),
        "latvia": ("vidzeme", 1_200_000),
        "zemgale": ("zemgale", 320_000),
        "latgale": ("latgale", 260_000),
    },
    "PNG": {
        "papua": ("papua-south", 1_200_000),
        "newguinea": ("png", 1_200_000),
        "interiorpapua": ("highlands", 4_500_000),
        "bismarck": ("bismarck", 500_000),
        "newbritain": ("bismarck", 500_000),
        "kaiserwilhelmsland": ("momase", 4_200_000),
    },
    "MOR": {
        "spanishafrica": ("north", 4_000_000),
        "marrakech": ("south", 12_000_000),
        "southernmorocco": ("south", 12_000_000),
        "westernsahara": ("ws", 400_000),
        "riodeoro": ("ws", 400_000),
    },
    "STC": {
        "hadhramaut": ("hadhramaut", 2_000_000),
        "arabianuk2": ("hadhramaut", 2_000_000),
        "socotra": ("socotra", 60_000),
        "aden": ("aden", 1_000_000),
        "provinceofaden": ("aden", 1_000_000),
    },
    "LAO": {
        "laos": ("vientiane", 4_800_000),
        "bassac": ("south", 2_000_000),
        "lanchang": ("north", 1_200_000),
    },
    "IRQ": {
        "alhajara": ("anbar", 1_800_000),
        "mosul": ("nineveh", 4_000_000),
        "iraqikurdistan": ("krg", 6_500_000),
    },
    "AFG": {
        "qataghan": ("northeast", 3_800_000),
        "maymanah": ("northwest", 2_400_000),
        "qandahar": ("south", 4_200_000),
    },
    "BUL": {
        "dobrudja": ("dobruja", 250_000),
        "dobrogea": ("dobruja", 250_000),
        "moesia": ("north", 1_800_000),
    },
    "SLV": {
        "northslovenia": ("east", 1_200_000),
        "northeasternslovenia": ("east", 1_200_000),
        "slovenianlittoral": ("coast", 330_000),
        "litorale": ("coast", 330_000),
    },
    "ISR": {
        "israel": ("israel", 9_400_000),
        "golanheights": ("golan", 50_000),
    },
    "CHL": {
        "magallanes": ("magallanes", 180_000),
        "southernchile": ("magallanes", 180_000),
        "easterisland": ("rapanui", 7_800),
    },
    "ARG": {
        "regionmesopotamica": ("mesopotamia", 3_600_000),
        "mesopotamia": ("mesopotamia", 3_600_000),
        "losandes": ("andes", 2_200_000),
    },
    "NGR": {
        "southernsahara": ("sahel", 3_000_000),
        "centralafrica": ("sahel", 3_000_000),
        "niger": ("south", 22_000_000),
    },
    "MRT": {
        "mauritania": ("populated", 4_200_000),
        "mauritaniandesert": ("desert", 400_000),
    },
    "TMS": {
        "ashkhabad": ("ahal", 5_500_000),
        "turkmenistan": ("ahal", 5_500_000),
        "tashauz": ("dashoguz", 1_500_000),
        "dashhowuz": ("dashoguz", 1_500_000),
    },
    "SOL": {
        "solomonislands": ("solomons", 720_000),
        "santacruzislands": ("nendo", 20_000),
        "nendo": ("nendo", 20_000),
    },
    "JAP": {
        "iwojima": ("ogasawara", 2_500),
        "marcusisland": ("minamitorishima", 200),
    },
    "AST": {
        "christmasisland": ("christmas", 1_700),
        "cocosislands": ("cocos", 600),
    },
    "RSF": {
        "northdarfur": ("northdarfur", 2_300_000),
        "southdarfur": ("southdarfur", 4_000_000),
    },
    "CHA": {
        "chad": ("south", 14_000_000),
        "bet": ("sahara", 500_000),
    },
    "AZA": {
        "kidal": ("kidal", 90_000),
        "tombouctou": ("north", 1_000_000),
        "gao": ("gao", 700_000),
    },
    "ANG": {
        "zambesi": ("east", 2_500_000),
        "southwestangola": ("southwest", 2_200_000),
    },
    "BRA": {
        "tocantins": ("tocantins", 1_600_000),
        "riobranco": ("roraima", 650_000),
    },
    "MAC": {
        "macedonia": ("northmacedonia", 1_800_000),
    },
    "CRO": {
        "croatia": ("slavonia", 700_000),
        "easterncroatia": ("slavonia", 700_000),
    },
    "SWE": {
        "janmayen": ("janmayen", 18),
    },
    "GRE": {"dodecanese": ("dodecanese", 200_000)},
    "POR": {"beja": ("beja", 140_000)},
    "ECU": {"ecuador": ("sierra-costa", 16_000_000)},
    "VEN": {"miranda": ("north", 12_000_000), "venezuela": ("north", 12_000_000)},
    "PRU": {"pastaza": ("amazonia", 500_000)},
    "COL": {"lalibertad": ("north", 12_000_000)},
    "ALG": {"algeriandesert": ("sahara", 1_200_000), "northafrica": ("sahara", 1_200_000)},
    "MZB": {"lourencomarques": ("south", 8_000_000), "eastafrica": ("south", 8_000_000)},
    "SUD": {"kurdufan": ("kordofan", 8_000_000), "sudan": ("kordofan", 8_000_000)},
    "EGY": {"westerndesert": ("western", 400_000), "westernegypt": ("western", 400_000)},
    "PHI": {"centralislands": ("visayas", 20_000_000)},
    "PAR": {"chacoboreal": ("chaco", 80_000)},
    "CAM": {"cambodia": ("cambodia", 16_000_000)},
    "EST": {"virumaa": ("idaviru", 130_000), "rakvere": ("laaneviru", 60_000)},
    "MON": {"gobi": ("gobi", 200_000)},
    "UZB": {"khiva": ("khorezm", 1_900_000)},
    "SSD": {"bahralghazal": ("bag", 3_500_000)},
    "MLI": {"kayeskoulikoro": ("west", 8_000_000)},
    "OMA": {"oman": ("interior", 1_200_000), "interioroman": ("interior", 1_200_000)},
    "MAL": {"limbang": ("sarawak-north", 50_000)},
}
